default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  database: agenda_edu

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: desafio_edu
  password: desafio123